### ISSUE TITLE
Create Teacher Accounts, verify and match to their courses

### ISSUE THREAD

**Issue by mmmcglone** [openstax/CZI-AP-Project#79]
This work will happen in late July.

**Comment by carlycurran** [comment]
Carly's prep notes: https://docs.google.com/document/d/1QuXIhSjrZZGxWZb1N8Z5vfIOtWCeQtfptHXunM4DYKs/edit

**Comment by mmmcglone** [comment]
Question for Jennifer/Jessica, when will the teachers know how many sections they'll have for the 2019-2020 school year?

**Comment by mmmcglone** [comment]
OpenStax Accounts for all pilot instructors have been created, accounts are verified and everyone is matched their correct course. 

Spreadsheet is available: @carlycurran will tag it here.

**Comment by carlycurran** [comment]
@mmmcglone @debshila here are the teacher accounts: https://docs.google.com/spreadsheets/d/1tpb_jLXQOV_hc7fZh8TQIt89dm4SLrZpUt_TrTHP5Fc/edit#gid=2116342508
